export const typicalStepsHome = [
  'Typescript',
  'NestJS',
  'ReactJs',
  'React Native',
  'NextJs',
  'CSharp',
  'HTML',
  'CSS',
  'SASS',
  'SCSS',
  'NodeJs',
  'NPM',
  'Yarn',  
  'PostgreSQL',  
  'MySQL',  
  'SQL Server',  
  'Redis',  
  'AWS',  
  'Docker',  
  'Git',  
  'GitLab',  
  'GitHub',
  'BitBucket',
  'Trello',
  'Jira',
  'Linux',
  'TailwindCSS',
  'Styled Components',
  'React Query',
  'React Hook Form',
  'React Router',
  'React Context',
]